version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-test-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks: 
      - docker-test-network

  api: 
    build: ./api
    container_name: docker-test-api
    command: npm run start
    restart: unless-stopped
    environment: 
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on: 
      - api_db
    networks: 
      - docker-test-network

  auth:
    build: ./auth
    container_name: docker-test-auth
    command: npm run start
    restart: unless-stopped
    environment: 
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on: 
      - auth_db
    networks: 
      - docker-test-network
  
  auth_db:
    image: mongo:latest
    container_name: docker-test-auth-db
    volumes: 
      - mongodb_auth:/data/db
    networks: 
      - docker-test-network

  api_db:
    image: mongo:latest
    container_name: docker-test-api-db
    volumes: 
      - mongodb_api:/data/db
    networks: 
      - docker-test-network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-test-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on: 
      - frontend
      - api
      - auth
    networks: 
      - docker-test-network

volumes: 
  mongodb_api:
  mongodb_auth:

networks: 
  docker-test-network: 
    driver: bridge